


const SETPRODUCTLIST = 'set_product'
const MENSPRODUCTSCATEGORIES = 'mens_categories'
const WOMENSPRODUCTSCATEGORIES = "womens"
const JWELERYPRODUCTSCATEGORIES = "jwelery"
const ELECTRONICSPRODUCTSCATEGORIES = "electronics"
const DETAILSPRODUCTS = 'details'
const UPDATEDPRODUCTS = 'updated'

//cart item

const ADDITEWISHLIST = "additemwishlist"
const DELETEITEMWISHLIST = "deleteitemwishlist"


export{SETPRODUCTLIST,
    MENSPRODUCTSCATEGORIES,
    WOMENSPRODUCTSCATEGORIES,
    JWELERYPRODUCTSCATEGORIES,
    ELECTRONICSPRODUCTSCATEGORIES,
    DETAILSPRODUCTS,
    UPDATEDPRODUCTS,
    ADDITEWISHLIST,
    DELETEITEMWISHLIST
}